# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 9 * * *'  # This cron expression triggers the workflow every day at midnight UTC

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v5 
      with:
        python-version: '3.10'
    - name: Get libraries
      run: |
        pip install requests
        pip install pandas
        pip install datetime
      
    - name: Run Python script
      run: python nhl.py

    - name: GIT commit and push files
      env:
        GH_PAT: ${{ secrets.PAT }}
      run: |
        git config --global user.name "CI"
        git config --global user.email "user@github.com"
        git add index.html
        git commit -m "Update index.html to newest version"
        git push https://x-access-token:${GH_PAT}@github.com/Strigssson/nhl.github.io.git HEAD:main
